### ISSUE TITLE
nPC.GLM, nPC.MLM and nPC.FarmCPU

### ISSUE THREAD

**Issue by shenweima** [xiaolei-lab/rMVP#39]
How to choose values of nPC.GLM, nPC.MLM and nPC.FarmCPU?
And, How to choose values of nPC.GLM, nPC.MLM and nPC.FarmCPU when I use K, CV.GLM, CV.MLM, CV.FarmCPU .
```
imMVP <- MVP(
    phe=phenotype,Ff
    geno=genotype,
    map=map,
    #K=Kinship,
    #CV.GLM=Covariates,
    #CV.MLM=Covariates,
    #CV.FarmCPU=Covariates,
    nPC.GLM=5,
    nPC.MLM=3,
    nPC.FarmCPU=3,
    priority="speed",
    #ncpus=10,
    vc.method="BRENT",
    maxLoop=10,
    method.bin="FaST-LMM",#"FaST-LMM","EMMA", "static"
    #permutation.threshold=TRUE,
    #permutation.rep=100,
    threshold=0.05,
    method=c("GLM", "MLM", "FarmCPU")
)
```

**Comment by XiaoleiLiuBio** [comment]
Hi there,

You can simply set the 'nPC.GLM, nPC.MLM and nPC.FarmCPU' to 3 or 5, either is ok. If the population structure information, e.g., breeds, is not included in the 'CV.GLM, CV.MLM, CV.FarmCPU ', we also suggest you set the number of PCs to 3 or 5.

Regards,
Xiaolei


---------------- 

---------- Origin message ----------
>From："shenweima" <notifications@github.com>
>To："XiaoleiLiuBio/rMVP" <rMVP@noreply.github.com>
>Subject：[XiaoleiLiuBio/rMVP] nPC.GLM, nPC.MLM and nPC.FarmCPU (#39)
>Date：2019-08-09 17:58:13
How to choose values of nPC.GLM, nPC.MLM and nPC.FarmCPU?
And, How to choose values of nPC.GLM, nPC.MLM and nPC.FarmCPU when I use K, CV.GLM, CV.MLM, CV.FarmCPU .
```
imMVP <- MVP(
phe=phenotype,Ff
geno=genotype,
map=map,
#K=Kinship,
#CV.GLM=Covariates,
#CV.MLM=Covariates,
#CV.FarmCPU=Covariates,
nPC.GLM=5,
nPC.MLM=3,
nPC.FarmCPU=3,
priority="speed",
#ncpus=10,
vc.method="BRENT",
maxLoop=10,
method.bin="FaST-LMM",#"FaST-LMM","EMMA", "static"
#permutation.threshold=TRUE,
#permutation.rep=100,
threshold=0.05,
method=c("GLM", "MLM", "FarmCPU")
)
```

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/XiaoleiLiuBio/rMVP/issues/39

**Comment by hyacz** [comment]
This issue is closed because it is no longer active.
