### ISSUE TITLE
Two minor bugs

### ISSUE THREAD

**Issue by philippbayer** [xiaolei-lab/rMVP#44]
Hi

Thank you for the recent improvements to this package!

I have two minor things:

1) When rMVP reports the significance level, it cuts off at 6 decimal places: https://github.com/xiaolei-lab/rMVP/blob/3acd666df3236da4ee40c52ffe30e8f45914eca0/R/MVP.r#L307
In my case I have so many SNPs that rMVP always prints `Significant level: 0.000000`. Perhaps it would be better to use scientific notation using `formatC(0.0000000000005, format = "e", digits = 2)`?

2) The files ending in signal.csv are very useful, is it possible there is a bug when only a single SNP is significant (which happens a lot with FarmCPU)?
Normally, I get a proper table with proper headers, but when I have only one SNP, I get a strange text-file like this:

<pre>
"x"
"SNP_5015"
"3"
"47924314"
"-6185.31927432418"
"1015.52184827578"
"1.50018111376143e-08"
</pre>

i.e., the single-row table got transposed. Funny enough it's just a cbind and a write.csv, I currently don't understand how this happens.

sessionInfo():
<pre>
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.10 (Santiago)

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
[1] rMVP_0.99.16     bigmemory_4.5.33 MASS_7.3-51.4

loaded via a namespace (and not attached):
[1] bigmemory.sri_0.1.3 compiler_3.6.1      tools_3.6.1
[4] Rcpp_1.0.2
</pre>

**Comment by XiaoleiLiuBio** [comment]
Hi Philipp Bayer,

Thank you very much for your nice suggestions. We will solve the problems as you suggested.

Cheers,
Xiaolei

---------------- 

---------- Origin message ----------
>From："Philipp Bayer" <notifications@github.com>
>To："xiaolei-lab/rMVP" <rMVP@noreply.github.com>
>Subject：[xiaolei-lab/rMVP] Two minor bugs (#44)
>Date：2019-10-28 11:42:28Hi

Thank you for the recent improvements to this package!

I have two minor things:

1) When rMVP reports the significance level, it cuts off at 6 decimal places: https://github.com/xiaolei-lab/rMVP/blob/3acd666df3236da4ee40c52ffe30e8f45914eca0/R/MVP.r#L307
In my case I have so many SNPs that rMVP always prints `Significant level: 0.000000`. Perhaps it would be better to use scientific notation using `formatC(0.0000000000005, format = "e", digits = 2)`?


2) The files ending in signal.csv are very useful, is it possible there is a bug when only a single SNP is significant (which happens a lot with FarmCPU)?
Normally, I get a proper table with proper headers, but when I have only one SNP, I get a strange text-file like this:

<pre>
"x"
"SNP_5015"
"3"
"47924314"
"-6185.31927432418"
"1015.52184827578"
"1.50018111376143e-08"
</pre>

i.e., the single-row table got transposed. Funny enough it's just a cbind and a write.csv, I currently don't understand how this happens.

sessionInfo():
<pre>
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.10 (Santiago)

locale:
[1] LC_CTYPE=en_AU.UTF-8 LC_NUMERIC=C
[3] LC_TIME=en_AU.UTF-8 LC_COLLATE=en_AU.UTF-8
[5] LC_MONETARY=en_AU.UTF-8 LC_MESSAGES=en_AU.UTF-8
[7] LC_PAPER=en_AU.UTF-8 LC_NAME=C
[9] LC_ADDRESS=C LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel stats graphics grDevices utils datasets methods
[8] base

other attached packages:
[1] rMVP_0.99.16 bigmemory_4.5.33 MASS_7.3-51.4

loaded via a namespace (and not attached):
[1] bigmemory.sri_0.1.3 compiler_3.6.1 tools_3.6.1
[4] Rcpp_1.0.2
</pre>

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/xiaolei-lab/rMVP/issues/44

**Comment by philippbayer** [comment]
Ah, cbind.data.frame fixed it, that explained why my minimal example using data-frames only didn't replicate that issue, thanks for the fast turnover :)
